name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 🚀 Features
    labels:
      - 'feature'
      - 'enhancement'
  - title: 🐛 Fixes
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: 🛠 Maintenance
    labels:
      - 'refactor'
      - 'documentation'
change-template: '- ${{change.title}} (#${{change.number}} by @${{change.author}})'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch