name: Linter Check
on:
  workflow_dispatch: {}
  # pull_request:
  #   branches:
  #     - DESARROLLO
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format on changed files
        run: |
          for file in $(find . -name "*.cs" -not -path "./Library/*" -not -path "./Temp/*"); do
            dotnet format --include "$file" --verify-no-changes --verbosity diagnostic
          done

      # - name: Run dotnet-format
      #   run: dotnet format UnitySolution.sln --verify-no-changes --verbosity diagnostic
