name: Linter Check
on:
  pull_request:
    branches:
      - DESARROLLO
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Find solution file
        run: |
          SOLUTION_FILE=$(find . -name "*.sln" | head -n 1)
          if [ -z "$SOLUTION_FILE" ]; then
            echo "No .sln file found."
            exit 1
          fi
          echo "solution_file=$SOLUTION_FILE" >> $GITHUB_ENV

      - name: Run dotnet-format
        run: dotnet format ${{ env.solution_file }} --verify-no-changes --verbosity diagnostic
