name: Discord Notifications
on:
    workflow_dispatch: {}
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set notification message
      - name: Set Notification Message
        id: set-message
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "::set-output name=message::✅ Build completado para la rama: ${{ github.ref_name }}"
          else
            echo "::set-output name=message::❌ Build fallido para la rama: ${{ github.ref_name }}"
          fi

      # Notify Discord
      - name: Notify Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "${{ steps.set-message.outputs.message }}"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
