name: Build Unity Project for WebGL and StandaloneWindows64
on:
  workflow_dispatch: {}
  push:
    branches:
      - PRE_PRODUCCION
      - PRODUCCION
jobs:
  free-disk-space:
    name: Free space disk on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

  build:
    name: Build ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    needs: free-disk-space
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
          - StandaloneWindows64
    env:
      UNITY_VERSION: ${{ vars.UNITY_VERSION }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - name: Set current date as env variable
        run: echo "START_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.UNITY_EMAIL }}" ] || [ -z "${{ secrets.UNITY_PASSWORD }}" ] || [ -z "${{ secrets.UNITY_LICENSE }}" ]; then
            echo "Required secrets are missing. Please check UNITY_EMAIL, UNITY_PASSWORD, and UNITY_LICENSE."
            exit 1
          fi

      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            Library
            Temp
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      # Build
      - name: Build
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ env.UNITY_VERSION }}
          versioning: Semantic
          buildName: ${{ vars.PROJECT_NAME }}

      # Upload Build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build ${{ vars.PROJECT_NAME }}-${{ matrix.targetPlatform }}-${{ github.run_id }}
          path: build/${{ matrix.targetPlatform }}
          if-no-files-found: "warn"

      - name: Get Artifact ID
        id: get-artifact-id
        run: |
          artifacts=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts")

          artifact_id=$(echo "$artifacts" | jq '.artifacts[0].id')
          echo "Artifact ID: $artifact_id"
          echo "artifact_id=$artifact_id" >> $GITHUB_OUTPUT

      # GH Pages
      - name: Deploy to GitHub Pages
        if: ${{ matrix.targetPlatform == 'WebGL' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build/${{ matrix.targetPlatform }}
          target-folder: .

      - name: Calculate Build Duration
        if: always()
        id: duration
        run: |
          echo "Workflow started at:  ${{ env.START_TIME }}"
          start_time=$(date -d " ${{ env.START_TIME }}"" +%s)
          end_time=$(date +%s)
          duration=$((end_time - start_time))

          echo "Start time (epoch): $start_time"
          echo "End time (epoch): $end_time"
          echo "Duration (seconds): $duration"

          hours=$((duration / 3600))
          minutes=$(((duration % 3600) / 60))
          seconds=$((duration % 60))
          formatted_duration=$(printf "%02d:%02d:%02d" $hours $minutes $seconds)

          echo "formatted_duration=${formatted_duration}" >> $GITHUB_ENV

        # Set notification message
      - name: Set Discord Notification Message
        if: always()
        id: set-message
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="✅ La build para la rama **${{ github.ref_name }}** se ha completado con éxito."
            COLOR=3066993
          else
            STATUS="❌ La build para la rama **${{ github.ref_name }}** ha fallado."
            COLOR=15158332
          fi

          LINK_ACTION="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

          if [ "${{ matrix.targetPlatform }}" == "StandaloneWindows64" ]; then
            LINK="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.get-artifact-id.outputs.artifact_id }}/zip"
            LINK_TEXT="Descargar"
          elif [ "${{ matrix.targetPlatform }}" == "WebGL" ]; then
            LINK="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
            LINK_TEXT="Ver"
          else
            LINK="LINK_ACTION"
            LINK_TEXT="Enlace no disponible. Ir a la acción"
          fi

          EMBED=$(jq -n \
            --arg description "$STATUS" \
            --argjson color $COLOR \
            --arg footerText "GitHub Actions - Discord Integration" \
            --arg footerIcon "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" \
            --arg rama "${{ github.ref_name }}" \
            --arg plataforma "${{ matrix.targetPlatform }}" \
            --arg workflowLink "[Ver detalles]($LINK_ACTION)" \
            --arg linkText "$LINK_TEXT" \
            --arg resultLink "[$LINK_TEXT]($LINK)" \
            --arg duracion "${{ env.formatted_duration }}" \
            --arg timestamp "$TIMESTAMP" \
            '
             {"tts": false,
              "embeds": [
                {
                  "description": $description,
                  "color": $color,
                  "footer": { "text": $footerText, "icon_url": $footerIcon },
                  "fields": [
                    { "name": "Rama ", "value": $rama },
                    { "name": "Plataforma ", "value": $plataforma },
                    { "name": "Workflow ", "value": $workflowLink },
                    { "name": "Enlace ", "value": $resultLink },
                    { "name": "Duración ", "value": $duracion }
                  ],
                  "author": {
                    "name": "Workflow terminado"
                  },
                  "timestamp": $timestamp
                }
              ]
            }')

          echo "message=$EMBED" >> $GITHUB_OUTPUT

        # Notify Discord
      - name: Notify Discord
        if: always()
        run: |
          echo "${{ steps.set-message.outputs.message }}"
          curl -H "Content-Type: application/json" \
          -d '${{ steps.set-message.outputs.message }}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
